version: '3.8'

services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: docker-nginx-app
    hostname: docker-nginx-host      
    environment:
      - CONTAINER_NAME=docker-nginx-container
    ports:
      - "80:80"
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: redis-container 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge